### PR TITLE
Release

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by hydrosquall** [comment]
This created a very tall changelog for 0.27.0 because there wasn't an existing release with tag 0.26.0 on GitHub. The next one will be tidier; we can do a manual one time cleanup using a local run of the changelog command, since the release page is editable.

**Comment by domoritz** [comment]
Will that remove the messages on the github issues and prs? 

Maybe for the next repos we should make sure that there is a release with a tag for the last version before we set up the automation.

**Comment by hydrosquall** [comment]
We can remove the messages if we disable the “released” plugin, the
intended benefit was making it clear which version each PR ended up getting
shipped in.

However, I acknowledge it come with the downside of creating many emails
for a repo owner, and perhaps the same benefit can be achieved by using
backlinks

https://github.com/intuit/auto/tree/main/plugins/released

> Maybe for the next repos we should make sure that there is a release with
a tag for the last version before we set up the automation.

Yep, agreed

**Comment by hydrosquall** [comment]
> This created a very tall changelog for 0.27.0 because there wasn't an existing release with tag 0.26.0 on GitHub. The next one will be tidier; we can do a manual one time cleanup using a local run of the changelog command, since the release page is editable.

I just updated the changelog for `0.27.0` by running this command locally:

```bash
yarn run auto changelog --dry-run --from v0.26.0 --to v0.27.0
```

Docs: https://intuit.github.io/auto/docs/generated/changelog

**Pull request merged**
